cmake_minimum_required(VERSION 3.20)

function(configure_required_cxxlib required_cxxlib)
    if(required_cxxlib STREQUAL "llvm-static")
        if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            message(FATAL_ERROR "require_cxxlib llvm-static requires a Clang C++ compiler")
        endif()
        add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-stdlib=libc++>")
        add_link_options(-stdlib=libc++)
        foreach(library_name libc++.a libc++abi.a)
            execute_process(
                COMMAND "${CMAKE_CXX_COMPILER}" --print-file-name=${library_name}
                OUTPUT_VARIABLE library_path
                OUTPUT_STRIP_TRAILING_WHITESPACE
                COMMAND_ERROR_IS_FATAL ANY)
            if(NOT IS_ABSOLUTE "${library_path}" OR NOT EXISTS "${library_path}")
                message(FATAL_ERROR "Could not find ${library_name} for ${CMAKE_CXX_COMPILER}")
            endif()
            list(APPEND required_cxxlib_archives "${library_path}")
        endforeach()
        set(YAE_REQUIRED_CXXLIB_ARCHIVES "${required_cxxlib_archives}" PARENT_SCOPE)
    elseif(required_cxxlib STREQUAL "gcc-static")
        if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:-stdlib=libstdc++>")
            add_link_options(-stdlib=libstdc++)
        elseif(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            message(FATAL_ERROR "require_cxxlib gcc-static requires a Clang or GNU C++ compiler")
        endif()
    else()
        message(FATAL_ERROR "Unknown require_cxxlib: ${required_cxxlib}")
    endif()

    set(YAE_REQUIRED_CXXLIB "${required_cxxlib}" PARENT_SCOPE)
endfunction()

function(link_required_cxxlib target_name)
    if(YAE_REQUIRED_CXXLIB STREQUAL "llvm-static")
        target_link_libraries(${target_name} PRIVATE ${YAE_REQUIRED_CXXLIB_ARCHIVES})
        target_link_options(${target_name} PRIVATE -nostdlib++)
    elseif(YAE_REQUIRED_CXXLIB STREQUAL "gcc-static")
        target_link_options(${target_name} PRIVATE -static-libstdc++)
    else()
        message(FATAL_ERROR "require_cxxlib was not configured")
    endif()
endfunction()
